/* PREGUNTAS */
INSERT INTO preguntas (difficulty, question, correct_answer, incorrect_answer1, incorrect_answer2, incorrect_answer3) VALUES
('easy', '¿En qué ciudad de la distopía del futuro alternativo de Half-Life 2 empiezas por primera vez?', 'Ciudad 17', 'Ciudad 18', 'Ciudad 6', 'Ciudad 45'),
('hard', '¿Cuál de los siguientes personajes NO es una candidata a matrimonio en el juego Stardew Valley?', 'Caroline', 'Haley', 'Leah', 'Abigail'),
('easy', 'La "invasión británica" fue un fenómeno cultural en la música donde las bandas de chicos británicos se hicieron populares en los EE. UU. ¿En qué década?', 'Años 50', 'Años 30', 'Años 40', 'Años 60'),
('easy', '¿ Cuál de las siguientes fuentes del derecho es la principal?', 'Constitución Nacional', 'leyes', 'Decretos', 'Tratados internacionales'),
('medium', '¿Cuántos balones de oro gano Lionel Andrés Messi?', '7', '5', '6', '8'),
('hard', '¿Cuál es la característica de un nudo gordiano?', 'Difícil de desatar', 'Fácil de desatar', 'Muscular', 'Psicológico / emocional'),
('easy', '¿Cuál de los siguientes no es el nombre de los hijos de Leo Messi y Antonela Roccuzzo?', 'Marcos', 'Mateo', 'Ciro', 'Thiago'),
('easy', '¿Qué hay en el centro de nuestra galaxia?', 'Un agujero negro', 'Una supernova', 'Un Cuasar', 'Un agujero de gusano'),
('easy', '¿Cuántos álbumes de estudio ha lanzado el dúo Daft Punk?', '4', '1', '2', '5'),
('easy', 'En "Mario & Sonic en los Juegos Olímpicos", ¿los personajes se dividen en cuántos tipos?', '4', '3', '5', '6'),
('easy', '¿Cuándo se estrenó la película "Con Air: Riesgo en el Aire"?', '1997', '1990', '1985', '1999'),
('easy', '¿Cómo se llama la isla en la que está construido "Jurassic Park"?', 'Isla Nublar', 'Isla Pena', 'Isla Sorna', 'Isla Muerta'),
('easy', '¿Cuál es la raíz cuadrada de 49?', '7', '9', '12', '4'),
('medium', '¿En qué motor de videojuegos se ejecuta el videojuego Quake 2?', 'iD Tech 2', 'iD Tech 3', 'iD Tech 1', 'Unreal engine'),
('easy', '¿Cuántos kilobytes hay en un gigabyte (en decimal)?', '1000000', '1048576', '1024', '1000'),
('easy', '¿Cómo se llamaba el submarino del capitán Nemo en "20.000 leguas de viaje submarino"?', 'El Nautilus', 'El Neptuno', 'El poseidon', 'La Atlántida'),
('easy', '¿Qué pintura no fue hecha por Vincent Van Gogh?', 'La novena ola', 'Dormitorio En Arles', 'Noche estrellada', 'Terraza del Café por la Noche'),
('hard', '¿Terry Gilliam fue un animador que trabajó con qué grupo de comedia británico?', 'Monty Python', 'Las golosinas', 'La Liga de los Caballeros', 'Los Penny Dreadfuls'),
('easy', '¿Cuál de los siguientes países no fue una potencia de eje durante la Segunda Guerra Mundial?', 'Unión Soviética', 'Japón', 'Alemania', 'Italia'),
('hard', '"Doctor Jones", "Turn Back Time" y "Barbie Girl" fueron los números uno del Reino Unido para qué grupo de Eurodance?', 'Agua', 'Vengaboys', 'Eiffel 65', 'Sash!'),
('easy', '¿Quién ganó el Campeonato Mundial de Pilotos de Fórmula 1 de 2016?', 'Nico Rosberg', 'Lewis Hamilton', 'Max Verstappen', 'Kimi Raikkonen'),
('hard', 'En el programa de televisión "Cheers", ¿Sam Malone fue un ex lanzador de relevo para qué equipo de béisbol?', 'Medias Rojas de Boston', 'Mets de Nueva York', 'Cerveceros de Milwaukee', 'Orioles de Baltimore'),
('easy', '¿Qué empresa desarrolla la serie de juegos de ritmo Rock Band?', 'Harmonix', 'Konami', 'Activision', 'Electronics Arts'),
('easy', '¿Qué álbum colaborativo fue lanzado por Kanye West y Jay-Z en 2011?', 'Mira el trono', 'Relativas distancias', 'Negocios inconclusos', 'Qué momento para estar vivo'),
('easy', '¿Quién en la mitología griega, quién llevó a los argonautas en busca del Vellocino de oro?', 'Jason', 'Castor', 'Dédalo', 'Odiseo'),
('easy', '¿Quién resulta ser el verdadero vencedor en la Batalla de Armageddon en Mortal Kombat?', 'Shao Kahn', 'Liu Kang', 'Shang Tsung', 'Raiden'),
('easy', '¿En qué país se fabricó el Trabant 601?', 'Alemania del Este', 'Unión Soviética', 'Hungría', 'Francia'),
('easy', '¿Cuál de estos NO es el nombre de un álbum lanzado por la cantautora inglesa Adele?', '12', '21', '19', '25'),
('easy', 'En el videojuego "Postal 2", ¿cómo se llama el perro de Postal Dude?', 'Champ', 'Krotchy', 'Snoopy', 'Duke'),
('easy', 'Cuando alguien no tiene experiencia, se dice que es de qué color.', 'Verde', 'Azul', 'Rojo', 'Amarillo'),
('easy', '¿La rinoplastia es un procedimiento quirúrgico en qué parte del cuerpo humano?', 'Nariz', 'Orejas', 'Barbilla', 'Cuello'),
('easy', '¿En qué país se encuentra Cory in the House?', 'Estados Unidos', 'Venezuela', 'Inglaterra', 'Canadá'),
('easy', '¿Qué actriz se casó con Michael Douglas en 2000?', 'Catherine Zeta Jones', 'Ruth Jones', 'Pam Ferris', 'Sara Sugarman'),
('easy', '¿De dónde es originario el origami?', 'China', 'Japón', 'Corea del Norte', 'Corea del Sur'),
('easy', '¿Quién es el cantante principal de Green Day?', 'Billie Joe Armstrong', 'Mike Dirnt', 'Sean Hughes', 'Tré Cool'),
('easy', '¿Cuáles de estos países permanecieron neutrales durante la Segunda Guerra Mundial?', 'Suiza', 'Reino Unido', 'Italia', 'Francia'),
('easy', '¿Que informático estadounidense creo el lenguaje de programación C', 'Dennis Ritchie', 'al-Khwārizmī', 'Tim Berners Lee', 'Willis bienes'),
('easy', '¿En qué año llegó Colón a América?', '1492', '1429', '1592', '1542'),
('medium', '¿En qué año se hundió el Titanic?', '1912', '1913', '1911', '1914'),
('hard', 'En 2013, ¿la estrella del pop virtual Hatsune Miku tenía un patrocinio con qué cadena de pizzas?', 'Dominos', 'Sabarros', 'Pizza Hut', 'Papa Johns'),
('easy', '¿Qué cervecería de propiedad estadounidense lideró el país en ventas por volumen en 2015?', 'DG Yuengling and Son, Inc', 'Boston Beer Company', 'Miller Coors', 'Anheuser Busch'),
('easy', '¿Cuál es el formato de imagen preferido para los logotipos en la base de datos de Wikimedia?', '.svg', '.jpeg', '.gif', '.jpeg'),
('easy', '¿Cuántos colores hay en un arcoíris?', '7', '8', '9', '9'),
('easy', '¿Cuántos cromosomas hay en las células del cuerpo humano?', '23', '22', '21', '24'),
('easy', '¿Cuál de estos NO es un personaje jugable en el videojuego Overwatch de 2016?', 'Invoker', 'Winston', 'Mercy', 'Zenyatta'),
('easy', '¿Qué obra de Shakespeare inspiró el musical "West Side Story"?', 'Romeo y Julieta', 'Macbeth', 'Othello', 'Hamlet'),
('easy', '¿Cual es la capital de Indonesia?', 'Jacarta', 'Medan', 'Palembang', 'Bandung'),
('easy', '¿Cuál es la capital de España?', 'Madrid', 'Toledo', 'Barcelona', 'Sevilla'),
('easy', '¿Cuál es el nombre en clave del sistema operativo móvil Android 7.0?', 'Nougat', 'Marshmallow', 'Ice Cream Sandwich', 'Jelly Bean'),
('easy', '¿La imagen de qué presidente aparece en el raro billete de 2 dólares estadounidense?', 'Thomas Jefferson', 'Martin Van Buren', 'John Quincy Adams', 'Ulysses Grant'),
('easy', '¿El hielo seco es la forma sólida de qué sustancia?', 'Dióxido de carbono', 'Amoníaco', 'Nitrógeno', 'Oxígeno'),
('hard', '¿Cuál es el apellido de la protagonista femenina principal de Final Fantasy VIII?', 'Heartilly', 'Almasy', 'Trepe', 'Loire'),
('easy', '¿Quién escribió "Harry Potter"?', 'J.K. Rowling', 'J.R.R. Tolkien', 'Terry Pratchett', 'Daniel Radcliffe'),
('easy', '¿Qué edad tenía Adolf Hitler cuando murió?', '56', '65', '45', '43'),
('hard', '¿En qué año se lanzó el primer juego de "Mass Effect"?', '2007', '2010', '2008', '2008'),
('easy', '¿Quién es el protagonista principal de Dead Space?', 'Isaac Clarke', 'Jefe principal', 'Comandante Shepard', 'Gordon Freeman'),
('easy', '¿En que año se lanzó Left 4 Dead 2?', '2009', '2010', '2008', '2007'),
('easy', '¿Con cuántos países comparte frontera terrestre Estados Unidos?', '2', '3', '1', '4'),
('easy', 'En un tablero de dardos, ¿qué número está directamente enfrente del número 1?', '19', '20', '12', '15'),
('hard', '"Minecraft" salió de la versión beta en 2011 durante una convención celebrada ¿en qué ciudad?', 'Las Vegas', 'Paris', 'Bellevue', 'London'),
('easy', '¿La serie de HBO "Game of Thrones" se basa en qué serie de libros?', 'Canción de hielo y fuego', 'Harry Potter', 'La rueda del tiempo', 'Nacidos de la bruma'),
('easy', '¿Cómo se llamaba el primer satélite terrestre artificial, lanzado por la Unión Soviética en 1957?', 'Sputnik 1', 'Voskhod 3KV', 'Zenit-2', 'Soyuz 7K-OK'),
('easy', '¿De qué color es el círculo de la bandera japonesa?', 'Rojo', 'Amarillo', 'Blanco', 'Negro'),
('medium', 'En la serie de videojuegos "Worms", ¿cuál de estas armas se ve afectada por el viento?', 'Bazuca', 'Ataque aéreo', 'Mortero', 'Granada'),
('easy', '¿Quién descubrió la penicilina?', 'Alexander Flemming', 'Marie Curie', 'Louis Pasteur', 'Alfred Nobel'),
('easy', 'En la mayoría de los videojuegos de FPS como Counter-Strike, ¿disparar a qué parte del cuerpo causa el mayor daño?', 'Cabeza', 'Brazo', 'Pecho', 'Pierna'),
('easy', '¿En qué año se lanzó League of Legends?', '2009', '2003', '2010', '2001'),
('easy', 'Which popular First Person Shooter (FPS) franchise, got a Real Time Strategy (RTS) game developed based on its universe?', 'Halo', 'Call of Duty', 'Battlefield', 'Borderlands'),
('medium', '¿En qué medio se creó "Clannad" por primera vez?', 'Novela visual', 'Anime', 'Novela ligera', 'Manga'),
('easy', '¿Cuántos planetas componen nuestro Sistema Solar?', '8', '9', '7', '6'),
('easy', 'Según Sherlock Holmes, "si eliminas lo imposible, lo que quede, por improbable que sea, debe ser el ....', 'Verdad', 'Respuesta', 'Causa', 'Fuente'),
('easy', '¿Cuál es el alter-ego del personaje de los cómics de DC "Superman"?', 'Clark Kent', 'Bruce Wayne', 'John Jones', 'Arthur Curry'),
('easy', '¿Qué animal participa en el experimento mental más famoso de Schrödinger?', 'Gato', 'Perro', 'Raton', 'Mariposa'),
('easy', '¿Cuál de estas criaturas mitológicas es mitad hombre y mitad caballo?', 'Centauro', 'Gorgona', 'Minotauro', 'Pegaso'),
('medium', '¿Quién es el protagonista del juego "The Walking Dead: Season One"?', 'Lee Everett', 'Clementina', 'Kenny', 'Rick Grimes'),
('hard', '¿Quién es el creador de la serie Super Smash Bros?', 'Masahiro Sakurai', 'Reggie Fils-Aime', 'Hideo Kojima', 'Bill Trinen'),
('hard', '¿En qué año se lanzó el juego "Fallout"?', '1997', '1998', '1999', '2000'),
('medium', '¿Cuál de los siguientes no es un personaje de la serie Street Fighter?', 'Mai Shiranui', 'Laura Matsuda', 'Sakura Kasugano', 'Ibuki'),
('easy', '¿Qué actor interpreta a "Walter White" en la serie "Breaking Bad"?', 'Bryan Cranston', 'Andrew Lincoln', 'Aaron Paul', 'RJ Mitte'),
('medium', '¿Cómo se llama el corgi del anime Cowboy Bebop?', 'Einstein', 'Joel', 'Rocket', 'Edward'),
('medium', '¿Cuándo se fundó Marvel Comics?', '1939', '1932', '1936', '1951'),
('easy', '¿Cuántas patas tienen las mariposas?', '6', '4', '8', '0'),
('easy', '¿Qué cantidad de bits equivale comúnmente a un byte?', '8', '64', '1', '1024'),
('easy', '"La primera regla es: no hablas de eso" ¿es una referencia a qué película?', 'Club de la lucha', 'American Pie', 'La isla', 'Lo Inimaginable'),
('easy', '¿Cuál de estos personajes es la mascota de la empresa de videojuegos SEGA?', 'Sonic', 'Alex Jidd', 'Opa-Opa', 'Mario Bros'),
('medium', '¿Cuál es el título de la canción en el menú principal de Halo?', 'Halo', 'Shadows', 'Suite Autumn', 'Opening Suite'),
('easy', '¿Cuál fue el segundo Pokémon de Ash Ketchum?', 'Caterpie', 'Pikachu', 'Pidgey', 'Charmander'),
('easy', '¿En qué empresa trabajaba Gabe Newell antes de fundar Valve Corporation?', 'Microsoft', 'Yahoo', 'Google', 'Apple'),
('medium', '¿Cuál es la profesión de la madre de Elon Musk, Maye Musk?', 'Modelo', 'Profesora', 'Programadora', 'Abogada'),
('easy', '¿Cuántos juegos de la serie Crash Bandicoot se lanzaron en la Playstation original?', '5', '6', '3', '4'),
('easy', '¿Cual es la capital de Jamaica?', 'Kingston', 'San Juan', 'Bridgetown', 'Nueva Delhi'),
('easy', '¿Cuántas estrellas tiene la bandera de Nueva Zelanda?', '4', '5', '2', '0'),
('easy', 'En South Park, ¿cuál es el apellido de Stan?', 'Marsh', 'Stotch', 'Broflovski', 'Tweak'),
('easy', 'Cuando alguien es cobarde, ¿de qué color se dice que tiene el vientre', 'Amarillo', 'Verde', 'Azul', 'Rojo'),
('medium', '¿Cuál de los siguientes NO es uno de los personajes principales del modo historia de Grand Theft Auto V?', 'Tommy Vercetti', 'Trevor Phillips', 'Michael de Santa', 'Franklin Clinton'),
('medium', 'En el anime "My Hero Academia", ¿qué personaje se muestra con la capacidad de manipular la gravedad?', 'Uraraka', 'Bakugo', 'Deku', 'Asui'),
('easy', 'El 71% de la superficie terrestre está formada por', 'Agua', 'Tierra', 'Desiertos', 'Bosques'),
('easy', '¿Cuántos lados tiene un heptágono?', '7', '8', '6', '5'),
('hard', '¿Cuántas obras de teatro se considera en general que Shakespeare ha escrito?', '37', '54', '43', '36'),
('easy', '¿Cómo se llama el papá de Harry Potter?', 'James Potter', 'Hairy Potter Sr.', 'Frank Potter', 'Joey Potter'),
('easy', '¿Qué elemento tiene el símbolo químico "Fe"?', 'Hierro', 'Plata', 'oro', 'Aluminio'),
('easy', '¿En qué año se produjo el desplome de Wall Street?', '1929', '1930', '1932', '1925'),
('easy', '¿Quién creó la serie "Metal Gear"?', 'Hideo Kojima', 'Gunpei Yokoi', 'Hiroshi Yamauchi', 'Shigeru Miyamoto'),
('easy', '¿Qué nombre se le da al personaje principal Chihiro en la película de 2001 "El viaje de Chihiro"?', 'Sen (mil)', 'Ichiman (diez mil)', 'Hyaku (cien)', 'Juu (diez)'),
('easy', '¿Qué número primo sigue después del 19?', '23', '27', '25', '21'),
('easy', '¿Cuál era el apellido de Dorothy en "El mago de Oz"?', 'Gale', 'Perkins', 'Parker', 'Day'),
('easy', '¿Qué país del Reino Unido tiene un dragón en su bandera?', 'Gales', 'Escocia', 'Inglaterra', 'Irlanda del Norte'),
('easy', '¿Qué equipo ganó la Copa Mundial de la FIFA 2014 en Brasil?', 'Alemania', 'Brasil', 'España', 'Argentina'),
('easy', '¿Cuántas estrellas tiene la bandera de la Unión Europea?', '12', '14', '10', '16'),
('hard', '¿Cómo se llama el león de peluche del anime Bleach?', 'Kon', 'Chad', 'Jo', 'Urdio'),
('easy', '¿Qué ciudad es la capital de los Estados Unidos de América?', 'Washington DC', 'Seattle', 'Los Angeles', 'Albany'),
('easy', '¿Qué estado de EE. UU. Tiene la mayor población?', 'California', 'Nueva York', 'Florida', 'Texas'),
('medium','¿Quién es el personaje principal de "La parábola de Stanley"?', 'Stanley', 'El jefe', 'El narrador', 'Nick'),
('easy', '¿Cuántos puntos hay en un solo dado?', '21', '24', '18', '23'),
('easy', '¿En qué año comenzó la Primera Guerra Mundial?', '1914', '1919', '1925', '1905'),
('easy', '¿Cuántas cuerdas tiene un violonchelo?', '4', '5', '8', '6'),
('easy', '¿Cuál es el nombre del robot naranja y blanco en "Star Wars: El despertar de la fuerza"?', 'BB-8', 'R2-D2', 'BB-3', 'C3PO'),
('easy', '¿Qué signo del zodíaco está representado por un par de escamas?', 'Libra', 'Sagitario', 'Aries', 'Capricornio'),
('medium', '¿Con qué empresa cooperó Valve en la creación de Vive?', 'HTC', 'Oculus', 'Razer', 'Google'),
('hard', '¿Cuál es el símbolo elemental del mercurio?', 'Hg', 'Me', 'Hy', 'Mc'),
('easy', '¿Cuándo se lanzó el iPhone?', '2007', '2006', '2005', '2004'),
('easy', '¿Quién es el principal antagonista de la franquicia Portal?', 'GLaDOS', 'Wheatley', 'Chell', 'Rick'),
('hard', 'En el juego Dark Souls, ¿cuál es el nombre de la región en la que te encuentras durante la mayor parte del juego?', 'Lordran', 'Drangleic', 'Oolacile', 'Catarina'),
('hard', 'En la película de animacion japonesa de 2012 "Niños lobo", ¿cómo se llaman los niños lobo?', 'Ame y Yuki', 'Ame y Hana', 'Chuck y Anna', 'Hana y Yuki'),
('medium', '¿Cuántos huesos hay en el cuerpo humano?', '206', '209', '200', '203'),
('easy', 'En la Copa Mundial de la FIFA 2014, ¿cuál fue el marcador final en el partido Brasil - Alemania?', '1-7', '2-6', '1-5', '1-6'),
('easy', '¿Cuál de los siguientes componentes sanguíneos forma un tapón en el lugar de las lesiones?', 'Plaquetas', 'globulos rojos', 'globulos blancos', 'Plasma'),
('easy', '¿Hipocampo es el nombre latino de qué criatura marina?', 'Caballo de mar', 'Delfín', 'Ballena', 'Pulpo'),
('hard', '¿Cuántos dientes tiene un conejo adulto?', '28', '24', '26', '30'),
('hard', '¿Cuántas zonas horarias tiene China?', '1', '2', '3', '4'),
('easy', 'En béisbol, ¿cuántas veces se debe lanzar la pelota fuera de la zona de strike antes de que se camine al bateador?', '4', '2', '3', '1'),
('easy', '¿Cuál es el apellido de Edward y Alphonse en el anime Fullmetal Alchemist?', 'Elric', 'Elwood', 'Ellis', 'Eliek'),
('medium', '¿Cuál de las siguientes es una clase del juego "Hearthstone"?', 'Sacerdote', 'Clérigo', 'Sabio', 'Monje'),
('easy', '¿La mascota de qué restaurante es un payaso?', 'Burger king', 'McDonalds', 'Whataburger', 'Sonic'),
('hard', '¿Qué estudio de animación animó el anime de 2016 "Mob Psycho 100"?', 'Bones', 'Shaft', 'A-1 Pictures', 'Madhouse'),
('easy', '¿Aproximadamente cuántos años tiene la Tierra?', '4.5 mil millones', '2.5 mil millones', '5,5 mil millones', '3,5 mil millones'),
('medium', '¿Quién es el creador de la serie manga "One Piece"?', 'Eiichiro Oda', 'Hayao Miyazaki', 'Yoshihiro Togashi', 'Masashi Kishimoto'),
('medium', 'En la serie de videojuegos Portal, ¿con qué nombre se fundó Aperture Science a principios de la década de 1940?', 'Aperture Fixtures', 'Aperture Lavatories', 'Wheatley Laboratories', 'Science Innovator'),
('medium', '¿Cuál es el nombre de la primera película de "Star Wars" por orden de lanzamiento?', 'Una nueva esperanza', 'La amenaza fantasma', 'La venganza de los Sith', 'El despertar de la fuerza'),
('medium', '¿Cuál es la fórmula química del amoniaco?', 'NH3', 'CH4', 'CO2', 'NO3'),
('medium', '¿En qué año surgió la banda de rock Queen?', '1970', '1973', '1968', '1975'),
('medium', '¿Quién es miembro de la banda británica Queen?', 'Todas son correctas', 'Freddie Mercury', 'Roger Taylor', 'John Deacon'),
('medium', '¿En qué año falleció Freddie Mercury?', '1991', '1981', '1993', '1987'),
('medium', '¿En qué año se estrenó la película Mujer Bonita?', '1990', '1999', '1992', '1994'),
('medium', '¿En qué año se estrenó la película Novia Fugitiva?', '1999', '1993', '1995', '1996'),
('medium', '¿En qué año se formó la banda argentina de rock Soda Stereo?', '1982', '1988', '1980', '1983'),
('medium', '¿En qué año se separó Soda Stereo?', '1997', '1994', '1995', '1992'),
('medium', '¿Cómo se llama el primer álbum de estudio de Soda Stereo?', 'Soda Stereo', 'Doble vida', 'Nada personal', 'Signos'),
('medium', '¿En qué año ocurrió el robo del siglo que dio origen a la película?', '2006', '2000', '2002', '2003'),
('medium', '¿Cuántos músculos tiene el ser humano?', 'Más de 600', '400 a 500', '300 a 400', '500 a 600')
('hard', '¿Cuántos tipos de tejido muscular existen?', '3', '2', '4', '1'),
('hard', '¿En qué año termino la segunda guerra mundial?', '1945', '1943', '1940', '1939'),
('medium', '¿Cuál es el país más grande del mundo?', 'Rusia', 'China', 'India', 'Estados Unidos'),
('hard', '¿En qué año empezó la segunda guerra mundial?', '1939', '1943', '1940', '1945'),
('medium', '¿Dónde hubo fuego…?', 'Cenizas quedan', 'Cenizas fueron', 'Cenizas hay', 'Ninguna es correcta'),
('medium', '¿En casa de herrero?', 'Cuchillo de palo', 'Cuchillo de madera', 'Ninguna es correcta', 'Cuchillo desafilado'),
('medium', '¿Cuál es un número primo?', '19', '47', '71', 'Todas son correctas'),
('hard', '¿Cuál es un numero compuesto?', '99', '11', '59', '23'),
('medium', '¿Cuál de los siguientes es el libro más vendido del mundo?', 'El Señor de los Anillos', 'El codigo Da Vinci', 'El Principito', 'Harry Potter y la Piedra Filosofal'),
('medium', '¿Qué nación fue sede de la Copa Mundial de la FIFA en 2006?', 'Alemania', 'Sudáfrica', 'Reino Unido', 'Brasil'),
('medium', '¿Qué empresa de Internet nació como una librería online llamada "Cadabra"?', 'Amazon', 'Overstock', 'eBay', 'Shopify'),
('medium', '¿Cuál es el primer elemento de la tabla periódica?', 'Hidrógeno', 'Oxígeno', 'Helio', 'Litio'),
('medium', '¿Quién creó la plataforma de distribución digital Steam?', 'Valve', 'Ubisoft', 'Electronic Arts', 'Pixeltail Games'),
('medium', '¿Qué ciudad tiene el aeropuerto más transitado del mundo?', 'Atlanta, Georgia USA', 'ISA de Chicago, Illinois', 'Londres, Inglaterra', 'Tokio, Japón'),
('medium', '¿Cuáles son los vasos sanguíneos más pequeños del cuerpo humano?', 'Capilares', 'Linfáticos', 'Arteriolas', 'Veinules'),
('medium', '¿De qué país es originario el piano?', 'Italia', 'Alemania', 'Francia', 'Austria'),
('medium', '¿Qué país regaló la Estatua de la Libertad a los Estados Unidos de América?', 'Francia', 'Inglaterra', 'España', 'Alemania'),
('medium', '¿En qué año se fundó Apple Inc.?', '1976', '1974', '1978', '1980'),
('medium', 'En el Ajedrez, ¿la Reina tiene el movimiento combinado de cuáles dos piezas?', 'Alfil y torre', 'Caballero y obispo', 'Torre y Rey', 'Rey y Caballero'),
('medium', '¿Qué equipo de fútbol ganó el Campeonato de la Copa América 2015?', 'Chile', 'Argentina', 'Brasil', 'Paraguay'),
('medium', '¿De qué color es la sangre no oxidada?', 'Roja', 'Verde', 'Púrpura', 'Naranja'),
('medium', '¿Cuál de los siguientes países fue el primero en enviar un objeto al espacio?', 'Alemania', 'USA', 'China', 'Rusia'),
('medium', 'El productor de EDM Marshmello actúa en vivo con ropa y una máscara de malvavisco ¿de qué color?', 'Blanco', 'Amarillo', 'Negro', 'Azul'),
('medium', '¿Cuál fue el título del primer sencillo de ABBA en el Reino Unido?', 'Waterloo', 'Fernando', 'Dancing Queen', 'Mamma Mia'),
('medium', 'En la serie "Portal", ¿quién era el asistente personal de Cave Johnson?', 'Caroline', 'Jane', 'Heather', 'Melissa'),
('medium', '¿Qué película del director de cine Stanley Kubrick se sabe que es una adaptación de una novela de Stephen King?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('medium', '¿Cómo se llama el dragón de Eragon en "Eragon"?', 'Saphira', 'Glaedr', 'Thorn', 'Arya'),
('medium', '¿A qué parte del cuerpo afecta la enfermedad de la osteoporosis?', 'Huesos', 'Corazón', 'Piel', 'Cerebro'),
('medium', '¿En qué parte del cuerpo se encuentra la "Tibia"?', 'Pierna', 'Brazo', 'Mano', 'Cabeza'),
('medium', '¿Cuál es la montaña más alta del mundo?', 'Monte Everest', 'Kangchenjunga', 'Monte Godwin Austen', 'Annapurna'),
('medium', '¿Cuál de estos lenguajes de programación es un lenguaje de bajo nivel?', 'Assembly', 'Python', 'C#', 'Pascal'),
('medium', '¿Cuál es la "potencia" de la célula animal eucariota?', 'Mitocondrias', 'Núcleo', 'Cloroplasto', 'Retículo endoplásmico'),
('hard', 'En el anime Noragami, ¿quién es uno de los principales protagonistas?', 'Yukine', 'Mayu', 'Karuha', 'Mineha'),
('medium', '¿Qué instrumento de metal tiene el tono más bajo en una orquesta?', 'Tuba', 'Trompeta', 'Trombon', 'Saxofón'),
('medium', '¿Cuál es el nombre de la Sirenita?', 'Ariel', 'Ivana', 'Adriana', 'Erza'),
('medium', 'Cuál fue el +ultimo club para el jugó profecionalmente Juan Román Riquelme?', 'Argentinos Juniors', 'Boca Juniors', 'El Barcelona', 'San Lorenzo'),
('medium', '¿Cómo se llama el personaje femenino principal de "The vampire diaries"?', 'Elena', 'Selena', 'Anabella', 'Christina'),
('medium', '¿Cuántos jugadores tiene cada equipo de béisbol en el campo de juego?', '9', '7', '5', '8'),
('medium', '¿Con qué estación comienza "Las cuatro estaciones" de Vivaldi?', 'Primavera', 'Verano', 'Invierno', 'Otoño'),
('medium', '¿Cómo se llama la novia de Popeye el Marino?', 'Olivia', 'Lavina', 'Maria', 'Martina'),
('hard', '¿En qué país actual están las ruinas de Troya?', 'Turquia', 'Grecia', 'Israel', 'Egipto'),
('hard', '¿Qué distrito de "Los juegos del hambre" lideró una cruenta rebelión un siglo antes de los hechoz que narra la saga?', 'El distrito 13', 'El distrito 11', 'El distrito 9', 'El distrito 4'),
('medium', '¿De qué color es la caja negra de los aviones?', 'Naranja', 'Negra', 'Blanca', 'Azul'),
('hard', '¿A qué músico de jazz lo apodaban "Satchmo"?', 'Louis Armstrong', 'Miles Davis', 'Charlie Parker', 'Duke Ellington'),
('easy', 'En Star Wars, Chewbacca es el copiloto de...¿de quién?', 'Han Solo', 'Luke Skywalker', 'Maestro Yoda', 'Obi Wan Kenobi'),
('hard', '¿En qué deporte gano Paula Pareto una medalla de iri en Río 2016?', 'Judo', 'Natación', 'Lucha libre', 'Karate'),
('medium', '¿Cuánto pesa aproximadamente un litro de aire?', 'Un gramo', 'Un miligramo', 'Un kilo', 'Un decagramo'),
('medium', '¿Qué océano es el más pequeño?', 'Ártico', 'Atlántico', 'Índico', 'Pacífico'),
('medium', '¿Cuál es el paí que produce más frutas kiwi en el mundo?', 'Italia', 'China', 'Japón', 'Nueva Zelanda'),
('medium', '¿Cuántas piecitas cuadradas forman cada pieza del Tetris?', '4', '2', '6', '5'),
('medium', '¿En qué posición básica del ballet los talones se tocan entre sí?', 'Primera', 'Segunda', 'Tercera', 'Cuarta'),
('hard', '¿En qué ciudad estadounidense se desarrolla la historia de "Greys Anatomy"?', 'Seattle', 'Nueva York', 'Los Ángeles', 'California'),
('medium', '¿Cuántas temporadas tuvo "Los Soprano"?', '6', '5', '10', '3'),
('medium', '¿Cuántas cuerdas tiene un violín?', '4', '6', '5', '3'),
('hard', '¿En qué país nació la cantante de salsa Celia Cruz?', 'Cuba', 'Panamá', 'Costa Rica', 'Argentina'),
('medium', '¿Cuál es el alimento más consumido en el mundo?', 'Arroz', 'Carne', 'Papa', 'Pescado'),
('medium', '¿Cuántos corazones tiene un rana?', '1', '2', '3', '4'),
('medium', '¿Cuál fue el país latinoamericano que más medallas obtuvo (19) durante los juegos Olímpicos de Río 2016?', 'Brasil', 'Argentina', 'Colombia', 'México'),
('medium', '¿Cuántos integrantes tenía la banda inglesa Queen?', '4', '5', '3', '6'),
('hard', '¿Cuál era el oficio de Pepper el personaje que hacía Angie Dickinson en una serie de TV?', 'Policía', 'Investigadora privada', 'Abogada', 'Chef'),
('hard', '¿En el billete argentino de qué valor hay un albatros?', '50', '5', '10', '20'),
('medium', '¿Qué ciudad fue elegida para albergar los Juegos Olímpicos 2020?', 'Tokio', 'Berlín', 'Londres', 'Los Angeles'),
('medium', 'En la canasta y en el burako, ¿qué numero se usa como comodín?', '2', '13', '1', '5'),
('hard', '¿En qué ámbito transcurría la serie "Cheers"?', 'Un bar', 'Una isla', 'Un hospital', 'Un restaurante'),
('medium', '¿Cuánto valen un caballo y un seis del mismo palo en la escoba del quince?', '15', '16', '10', '7'),
('medium', '¿Cuántos ojos tiene Turanga Leela, personaje de Futurama?', '1', '2', '3', '8'),
('medium', '¿En qué país nace el río Parana?', 'Brarsil', 'Argentina', 'Bolivia', 'Ecuador'),
('medium', '¿Cómo se llama el partido que lidera Pablo Iglesias en España?', 'Podemos', 'Queremos', 'Sabemos', 'Hacemos'),
('medium', '¿Qué equipo ha ganado más veces la Champions League?', 'Real Madrid', 'Barcelona', 'Bayern Munich', 'PSG'),
('medium', '¿Cuántos corazones tiene una araña?', '1', '2', '3', '5'),
('medium', '¿Qué país fue anfitrión de la Copa Mundial de Fútbol dos ediciones seguidas?', 'Ninguno', 'Brasil', 'Inglaterra', 'Argentina'),
('medium', '¿De que país es originario el vallenato?', 'Colombia', 'Cuba', 'España', 'Costa Rica'),
('easy', '¿Quiém es el héroe que protege a Ciudad Gótica?', 'Batman', 'Superman', 'Flash', 'Spider-man'),
('medium', '¿De qué raza era la perra "Lasie"?', 'Collie', 'Ovejero alemán', 'Pastor inglés', 'Husky'),
('medium', '¿Qué país es el principal consumidor de palmito?', 'Francia', 'Italia', 'Argentina', 'Brasil'),
('medium', '¿Qué cree tener el hipocondríaco aunque no lo tiene?', 'Enfermedades', 'Perseguidores', 'Alas', 'Dinero'),
('easy', '¿En qué historia apareció primero el personaje Campanita?', 'Peter Pan', 'Hansel y gretel', 'La bella durmiente', 'La bella y la bestia'),
('hard', '¿Que enseña Will Schuester en la escuela en la cual transcurre "Glee"?', 'Español', 'Danza', 'Canto', 'Gimnasia'),
('medium', '¿Cuántos eran los locos de una novela de Roberto Arlt?', '7', '2', '0', '5'),
('easy', '¿A quién le dice Darth Vader "Yo soy tu padre"?', 'Luke Skywalker', 'Yoda', 'Anakin Skywalker', 'Obi-Wan Kenobi'),
('medium', '¿Cuántas docenas hay en una gruesa?', '12', '10', '6', '100'),
('medium', '¿A qué animal domestica El principito?', 'Zorro', 'Serpiente', 'Ardilla', 'Cocodrilo'),
('medium', '¿Cuántas veces aproximadamente, cabría la tierra en la disntancia de la Tierra a la luna?', '30', '300', '3000', '1300'),
('easy', '¿Cómo se el payaso de Los Simpson?', 'Krusty', 'Rusty', 'Lusty', 'Duskry'),
('medium', '¿Cuántos muñequitos hay en cada equipo en el metegol?', '11', '12', '10', '5'),
('medium', '¿De qué color era la ballena Moby Dick?', 'Blanca', 'Negra', 'Azul', 'Ninguna de las anteriores'),
('medium', '¿Qué serie de libros vendió 450 millones de ejemplares entre 1997 y 2014?', 'Harry potter', 'Los juegos del hambre', 'Crepúsculo', 'La rueda del tiempo'),
('easy', '¿Qué animal era Remy, el protagonista de "Ratatouille"?', 'Rata', 'Gato', 'Mono', 'Perro'),
('hard', '¿Por qué nombre se más conocido el personaje literario Lord Greystoke?', 'Tarzán', 'Sherlock Holmes', 'Phileas Fogg', 'Peter Pan'),
('medium', 'Shenlon y Leonard comparten un departamento ¿En qué serie?', 'Big bang theory', 'Friends', 'Two and a half men', 'iCarly'),
('medium', '¿Cuál es la isla más grande del mundo?', 'Groenlandia', 'Sumatra', 'Java', 'Cuba'),
('medium', '¿A quién esperaba Penélope?', 'Ulises', 'Jasón', 'Auiles', 'Hercules'),
('hard', '¿En qué océano estaba la isla de la serie "Lost"?', 'Pacífico', 'Índico', 'Atlántico', 'Ártico'),
('medium', 'En el mundial de fútbol del 78 Argentina perdió un solo partido ¿Contra quién?', 'Italia', 'España', 'Alemania', 'Francia'),
('hard', '¿Contra que país debutó Argentina ganando 2 a 1 en la Copa America 2016?', 'Chile', 'Colombia', 'Estados Unidos', 'Brasil'),
('medium', '¿Qué instrumento musical toca Sherlock Holmes?', 'Violín', 'Flauta', 'Piano', 'Ninguno'),
('medium', '¿Cuál es la mayor distancia que se dispta en natación, en los Juegos Olímpicos?', '1500', '1000', '2000', '2500'),
('easy', '¿Qué superhéroe tiene un cuartel general en la Fortaleza de la Ssoledad?', 'Superman', 'Batman', 'Flash', 'Iron-man'),
('medium', '¿Qué le falta a la "Venus de Milo?', 'Los brazos', 'La cabeza', 'Las piernas', 'Los dedos'),
('medium', '¿A qué primate nos asemejamos más, genéticamente, los humanos?', 'Chimpancé', 'Gorilla', 'Mono', 'Orangután'),
('medium', '¿Cuál es el mayor animal que haya existido jamás en nuestro planeta?', 'Ballena azul', 'Tiranosautio Rex', 'Mamut', 'Elefante'),
('easy', '¿Qué continente alberga el 70% del agua dulce del planeta?', 'Antartida', 'Asia', 'Oceanía', 'America'),
('hard', '¿Qué tenista ostenta el record de 109 titulos de la ATP?', 'Connors', 'Nadal', 'Federer', 'Lendl'),
('medium', '¿En que deporte hay tres minutos de acción y uno de descanso, alternadamente?', 'Boxeo', 'Karate', 'Judo', 'Taekwondo'),
('medium', 'La que empolló al Patito Feo ¿Que fue?', 'Pata', 'Gansa', 'Gallina', 'Cisne'),
('medium', '¿Quién le pone la voz al Gato con Botas?', 'Antonio Banderas', 'Rivky Martin', 'Miguel Bosé', 'Chayanne'),
('medium', '¿Quién ganó en 2016 el Oscar 2015 a mejor actor?', 'Leonardo Di Caprio', 'Johnny Depp', 'Matt Damon', 'Michael Fassbender'),
('medium', '¿Quién fue el hijo más famoso de Doña Gregoria Matorras?', 'San Martín', 'Belgrano', 'Paso', 'Sarmiento'),
('hard', '¿En qué país, ademas de Polonia, se disputó la Eurocopa 2012?', 'Ucrania', 'Bulgaria', 'Rumania', 'Francia'),
('medium', '¿Qué actriz protagoniza "El secreto de sus ojos"?', 'Soledad Villamil', 'Laura Novoa', 'Cacilia Roth', 'Carina Zampini'),
('hard', 'El acueducto de Segovia fue construido en el siglo II para llevar agua a la ciudad desde un río ubicado a 17 km, tarea que cumplió hasta el siglo..¿hasta que siglo??', 'XX', 'VII', 'XV', 'XII'),
('medium', '¿Cuántos pies tien una almeja?', '1', '2', '4', '0'),
('medium', 'Gary Medel es unjugador de fútbol nacido... ¿en que país?', 'Chile', 'Uruguay', 'Brasil', 'Colombia'),
('easy', '¿Quién protagonizó "Mujer bonita"?', 'Julia Roberts', 'Lindsay Wagner', 'Natalie Wood', 'Sofía Loren'),
('easy', '¿Cuántas eran las sombras de Grey?', '50', '60', '10', '70'),
('medium', '¿De qué color se ve el cielo en la Luna?', 'Negro', 'Rojo', 'Blanco', 'Celeste'),
('medium', '¿Qué País obtuvo la medalla dorada en hockey sobre césped en Río 2016?', 'Argentina', 'Bélgica', 'Holanda', 'Australia'),
('medium', 'Los Diablos Rojos es el apodo de... ¿de qué equipo de fútbol argentino?', 'Independiente', 'Colón', 'River', 'Racing'),
('medium', '¿Cuál fue el volcán cuya lava sepultó a Pompeya?', 'Vesubio', 'Monte Amiata', 'Lanín', 'Etna'),
('hard', '¿Qué instrumento tocaba principalmente Astor Piazzolla?', 'Bandonéon', 'Guitarra', 'Clarinete', 'Trompeta'),
('easy', 'Las hermanoas de Marge Simpson se llaman Selma y... ¿y cuál es la otra?', 'Patty', 'Wanda', 'Dilma', 'Vilma')
('medium', '¿con qué chocó el Titanic en su primer viaje trasatlántico?', 'Con un iceberg', 'Con otro barco', 'Con un arrecife', 'Ninguna es correcta'),
('medium', '¿Qué selección nacional empezó a dirigir José Pekerman en 2012?', 'Colombiana', 'Paraguaya', 'Chilena', 'Argentina'),
('medium', '¿Quiénes se comieron las migas de pan que Hansel y Gretel iban dejando en el camino?', 'Los pájaros', 'Los zorros', 'Los conejos', 'Ninguna es correcta'),
('medium', '¿Cómo se llama la serie de Matt Groening ambientada en el futuro?', 'Futurama', 'Volver al futuro', 'Ir al futuro', 'Futuro lejano'),
('medium', '¿Qué animal es Calamardo en Bob Esponja?', 'Pulpo', 'Estrella', 'Pez', 'Cangrejo'),
('medium', '¿Dónde pesa más un astronauta, en su casa o en la Luna?', 'En su casa', 'Pesa lo mismo', 'No sabe no contesta', 'En la Luna'),
('medium', '¿A quién se llama el caballero de la triste figura?', 'A Don Quijote', 'A Merlín', 'A Hamlet', 'A Robin Hood'),
('medium', '¿Qué actor es el protagonista de la película El ciudadano ilustre?', 'Oscar Martínez', 'Lito Cruz', 'Guillermo Francella', 'Leonardo Sbaraglia'),
('medium', '¿Quién le cortó la mano al Capitán Garfio?', 'Peter Pan', 'Un cocodrilo', 'Un tiburón', 'El mismo'),
('medium', '¿Cuál es el arma de Thor en la mitología nórdica?', 'Un martillo', 'No tiene arma', 'Un hacha de dos filos', 'Ninguna es correcta'),
('medium', '¿En que club empezó su carrera como entrenador el Cholo Sieone?', 'Racing', 'Boca', 'Estudiantes', 'River'),
('medium', '¿A qué edad murió Michael Jackson?', '50', '40', '42', '47'),
('medium', '¿En qué año murió Michael Jackson?', '2009', '2010', '2007', '2008')
('medium', '¿Qué color de guantes está prohibido en el boxeo?', 'Ninguno', 'Verde fluo', 'Naranja', 'Rosa'),
('medium', '¿De qué parte del papiro se extrae el material para escribir', 'Del tallo', 'Ninguna es correcta', 'De las hojas', 'De la raíz'),
('medium', '¿Cuál es la hortaliza más consumida en Argentina?', 'El tomate', 'Ninguna es correcta', 'La zanahoria', 'La lechuga'),
('medium', '¿Quién es el realizador de Los 8 más odiados?', 'Quentin Tarantino', 'Martin Scorsese', 'George Lucas', 'Ninguna es correcta'),
('medium', '¿Cuántos dedos tiene una cotorra en cada pata?', '4', 'No tiene', '2', '3'),
('medium', '¿Qué fue Roland Garros?', 'Un aviador', 'Un basquetbolista', 'Un tenista profesional', 'Un futbolista'),
('medium', '¿En qué año se estrenó Mamma Mia?', '2008', '2004', '2005', '2007'),
('medium', '¿Qué actriz protagonizó Esperanza Mía?', 'Mariana Espósito', 'Martina Stoessel', 'Julieta Díaz', 'Ángela Torres'),
('medium', '¿Cuántas veces fue elegido presidente Juan Domingo Perón?', '3', '4', '2', '1'),
('medium', '¿En qué juego hay puras, impuras, pozos y tapas?', 'En la canasta', 'En el burako', 'En el bridge', 'Todas son correctas'),
('medium', '¿En qué país nació Julio Cortázar?', 'Bélgica', 'Uruguay', 'Francia', 'Argentina'),
('medium', '¿Cuál es el máximo valor de una flor en el truco?', '38', '41', '40', '33'),
('medium', '¿Qué ave está en los escudos de Chile, Colombia, Bolivia y Ecuador?', 'Cóndor', 'Zopilote', 'Buitre', 'Águila'),
('medium', '¿Cuánto duró la guerra de los 100 años?', '116', '108', '99', '100'),
('medium', '¿A través de qué país tuvo que salir Perón después del golpe militar de 1955?', 'Paraguay', 'Perú', 'Chile', 'Uruguay'),
('medium', '¿Quiénes eran Los que hacían sus casas de piedra?', 'Los Diaguitas', 'Los onas', 'Los Mapuches', 'Los Rapanui'),
('medium', '¿Cuántos años hacía que River no ganaba una Copa Libertadores antes de la del 2015?', '19', '17', '22', '21'),
('medium', '¿Cuál es el país de origen del bandoneón?', 'Alemania', 'Nigeria', 'Grecia', 'Argentina'),
('medium', '¿De qué color son las pelotas del cróquet, además de azul?', 'Todas son correctas', 'Roja', 'Negra', 'Amarilla'),
('medium', '¿En qué ciudad fue asesinado John Lennon?', 'Nueva York', 'Washington', 'Londres', 'Nueva Orleans'),
('medium', '¿Cuánto peso pueden levantar las hormigas tejedoras?', 'Hasta 100 veces su peso', '80 veces su peso', '50 veces su peso', '40 veces su peso'),
('medium', '¿siguiendo a quien entra Alicia en el Pais de las maravillas?', 'Al conejo', 'A su gata', 'Al sombrerero loco', 'A nadie'),
('medium', '¿Qué centro de esquí se halla al pie del Aconcagua?', 'Penitentes', 'Cerro Bayo', 'Martial', 'Cerro Catedral'),
('medium', '¿Cuál es el nombre de la cantante y actriz protagonista de Violeta?', 'Martina', 'Marina', 'Luisana', 'Mariana'),
('medium', '¿En qué ciudad japonesa esta la fábrica Toyota?', 'Toyota', 'Hiroshima', 'Kioto', 'Tokio'),
('medium', '¿Cuántas hermanastras tiene Cenicienta?', '2', '1', 'No tiene', '3'),
('medium', '¿Cuántas hermanastras tiene Rapunzel?', 'No tiene', '1', '2', '3'),
('medium', '¿De dónde proviene el formato del programa Gran Hermano?', 'Holanda', 'EE.UU.', 'España', 'Argentina'),
('medium', '¿Cuántos pares de patas tienen los ciempiés?', '21', '15', '30', '50'),
('medium', '¿Cómo se llama la novel El amor en los tiempos del…?', 'Cólera', 'Desasosiego', 'Caos', 'Derrumbe'),
('medium', '¿En qué ciudad nació Cristina Fernández de Kirchner?', 'La Plata', 'Buenos Aires', 'Río Gallegos', 'Rosario'),
('medium', '¿Qué club fue fundado en Pompeya su estadio está en Parque Patricios?', 'Huracán', 'Boca', 'River', 'Rivadavia'),
('medium', '¿Cómo se llama la amiga de Harry Potter?', 'Hermione', 'Simone', 'Elsa', 'Ron'),
('medium', '¿Qué medalla obtuvo Juan Martín del Potro en Río 2016?', 'Plata', 'Oro', 'Bronce', 'No obtuvo'),
('medium', '¿Cuántas veces si disputó en Alemania el mundial de futbol?', '2', '1', '4', '3'),
('medium', '¿A quién pertenece el búho Hedwig?', 'Harry Potter', 'Hermione', 'Maléfica', 'Ron'),
('medium', '¿Cuántas fichas dobles hay en el dominó?', '7', '9', '5', '3'),
('medium', '¿Qué profesión tenía Watson, el amigo de Sherlock Holmes?', 'Médico', 'Abogado', 'Policía', 'Bombero'),
('medium', '¿Qué actriz fue pareja de Gael García Bernal durante muchos años?', 'Dolores Fonzi', 'Luisana Lopilato', 'Romina Gaetani', 'Carla Peterson'),
('medium', '¿Qué prócer se llamaba Manuel José Joaquín del Corazón de Jesús?', 'Belgrano', 'San Martín', 'Sarmiento', 'Rivadavia'),
('hard', '¿Qué papa vino después de Pablo VI?', 'Juan Pablo I', 'Pio XII', 'Benedicto XVI', 'Juan Pablo II'),
('hard', '¿Qué pasa si un luchador de sumo pierde en el combate su vestimenta, el taparrabos mawashi?', 'Pierde el combate', 'Nada, sigue desnudo', 'Se suspende el combate', 'Ninguna es correcta'),
('hard', '¿Cuántas caras tienen un cono truncado?', '3', '1', '2', '4'),
('hard', '¿Cuántas veces fue Alain Prost campeón mundial de Fórmula 1?', '4', '5', '2', '3'),
('hard', '¿Qué tiempo musical es más rápido?', 'El allegro', 'El andante', 'Los dos iguales', 'Ninguna es correcta'),
('hard', '¿Qué animal fue domesticado primero?', 'El cerdo', 'El caballo', 'El cerdo no fue domesticado', 'El caballo no fue domesticado'),
('hard', '¿Cuál es la materia que no está hecha de átomos?', 'Los electrones', 'Todas son correctas', 'Los neutrones', 'Los protones'),
('hard', '¿De qué nacionalidad es el piloto Juan Pablo Montoya?', 'Colombiano', 'Ecuatoriano', 'Paraguayo', 'Venezolano'),
('hard', '¿De quién es la letra del tango Mi noche triste?', 'Pascual Contursi', 'Homero Manzi', 'Alfredo Le Pera', 'Carlos Gardel'),
('hard', '¿Cómo termina la seri Los Soprano?', 'Con una cena familiar', 'Un viaje', 'Un asesinato', 'Todas son correctas'),
('hard', '¿En qué país está el puente de Aviñón?', 'Francia', 'Italia', 'No existe', 'España'),
('hard', '¿Qué serie transcurría en Peyton Place?', 'La caldera del diablo', 'Todas son correctas', 'Dinastía', 'Blanco y negro'),
('hard', '¿Qué es lo que está integrado en un circuito integrado?', 'Los transistores', 'Todas son correctas', 'Los cables', 'Las resistencias'),
('hard', '¿Cuál es la profesión de Glenn Close en la serie Damages?', 'Abogada', 'Psicóloga', 'Médica', 'Policía'),
('hard', '¿Cuántas republicas hay en la Península Ibérica?', '1', '4', '2', '3'),
('hard', '¿De qué ciudad es el club Atlético Nacional que ganó la copa libertadores 2016?', 'Medellín', 'Bogotá', 'Cali', 'Ninguna es correcta'),
('hard', '¿Quién dirigió la película La guerra de los mundos?', 'Steve Spielberg', 'Lawrence Kasdan', 'Tim Burton', 'Ninguna es correcta'),
('hard', '¿En qué banda cantaba Liam Gallagher en los 90?', 'Oasis', 'Blind Melon', 'Foo Fighters', 'Ninguna es correcta'),
('hard', '¿Qué actor norteamericano entrevistó a El Chapo Guzmán para la revista Rolling Stone?', 'Sean Penn', 'Woody Harrelson', 'Mark Ruffalo', 'Ninguna es correcta'),
('hard', '¿Qué país tiene su propio mapa en su bandera?', 'Chipre', 'Laos', 'Tailandia', 'Lituania'),
('hard', '¿A qué velocidad puede galopar un rinoceronte?', '40 km por hora ', '50 km por hora ', '30 km por hora ', '20 km por hora'),
('hard', '¿Qué filósofo practicó la lucha en su juventud?', 'Platón', 'Sócrates', 'Kant', 'Séneca'),
('hard', '¿En qué club de Liverpool se inició la carrera de Los Beatles?', 'The Cavern Club', 'Ninguna es correcta', 'The Black Tie', 'The Masters Club '),
('hard', '¿Qué constructor ganó más carreras de Fórmula 1?', 'Ferrari', 'McLaren', 'Lotus', 'Ninguna es correcta'),
('hard', '¿Alfred Hitchcock de qué nacionalidad es?', 'Británico', 'Alemán', 'Español', 'Estadounidense'),
('hard', '¿Qué pintor francés es conocido por sus cuados con bailarinas?', 'Edgar Degas', 'Henri Matisse', 'Paul Cézanne', 'Edouard Manet'),
('hard', '¿-con qué actriz grabó Robbie Williams el video Something Stupid?', 'Nicole Kidman', 'Charlize Theron', 'Scarlett Johansson', 'Ninguna es correcta'),
('hard', '¿Cuánto estuvo el pueblo paraguayo sin votar a un candidato presidencial que no fuera Stroessner?', '30', '28', '32', '33'),
('hard', '¿en qué mes de 1975 se realizaron los últimos fusilamientos de la dictadura de Francisco Franco?', 'Septiembre', 'Agosto', 'Noviembre', 'Octubre'),
('hard', '¿Cómo se llamaban los mercenarios que actuaron en Malvinas?', 'Gurkas', 'Tugs', 'Siks', 'Ninguna es correcta')
('hard', '¿Qué parentesco tenía Cleopatra, soberana egipcia, con quien contrajo matrimonio?', 'Hermanos', 'Primos', 'Tío y sobrina', 'Padre e hija'),
('hard', '¿Quién fue el presidente de EE.UU. que decidió tirar la bomba atómica en Hiroshima?', 'Harry Truman', 'Edgar Hoover', 'Franklin Roosevelt', 'Ninguna es correcta'),
('hard', '¿Qué parte del cuerpo se cortaban las guerreras mitológicas llamadas amazonas para facilitar el disparo de las flechas?', 'Un pecho', 'La nariz', 'Una oreja', 'Un dedo'),
('hard', '¿Qué político le cortó la cara a Lisandro de la Torre en un duelo de la década del 20?', 'Yrigoyen', 'Alvear', 'Sáenz Peña', 'Rosas'),
('hard', '¿Qué país estuvo durante 33 años en estado de sitio, finaizado en 1989?', 'Paraguay', 'Ecuador', 'Perú', 'Venezuela'),
('hard', '¿En qué año muere Gandhi?', '1948', '1952', '1939', '1945'),
('hard', '¿Con que golpeo Nikita Khrushchev la mesa para pedir silencio en una sesión de la ONU?', 'Con un zapato', 'con un bastón', 'Con los puños', 'Martillo'),
('hard', '¿Qué actriz interpreta el papel de Arya Stark en Juego de tronos?', 'Maisie Williams', 'Michelle Fairley', 'Emilia Clarke', 'Lena Headey'),
('hard', '¿Cuántas neuronas hay como promedio en el cerebro humano?', 'Mas de 80 millones', 'Entre 50 y 80 millones', 'Entre 10 y 40 millones', 'Menos de 10 millones'),
('hard', '¿En qué juego se puede apostar a líneas, enteros, calles y cuadros?', 'Ruleta', 'Siete y medio', 'Póker', 'Lotería'),
('hard', '¿Quién intrepreta a La viuda negra en las ficciones de Marvel?', 'Scarlett Johansson', 'Jessica Alba', 'Carrie Fisher', 'Angelina Jolie'),
('hard', '¿Contra qué país jugo EE.uu: la final de baloncesto en Río 2016?', 'Serbia', 'Argentina', 'Australia', 'España'),
('hard', '¿Cómo se llama la hermana de Drake y Josh?', 'Megan', 'Rachel', 'Susan', 'Carly'),
('hard', '¿Quién dirigió al Olympique de Marsella entre 2014 y 2015?', 'Bielsa', 'Tata Martino', 'Pekerman', 'Sampaoli'),
('hard', '¿A qué se dedica el forense Dexter Morgan en sus ratos libres?', 'Asesino serial', 'Músico', 'Jardinero', 'Futbolista'),
('hard', '¿Por qué nombre fue conocido el futbolista Waldir Pereira?', 'Didi', 'Pelé', 'Kaká', 'Waldir'),
('hard', '¿De dónde es originario el plato Chop Suey?', 'China', 'Alemania', 'Corea', 'Japón'),
('hard', '¿De dónde es el equipo de futbol Everest?', 'Ecuador', 'Croacia', 'Nepal', 'China'),
('hard', '¿Qué son Vega, Capella, Arturo y Proción?', 'Estrellas', 'Tipos de flores naranjas', 'Amapolas', 'Mariposas'),
('hard', '¿Qué actriz interpreta a Carrie Brandshaw en las películas Sex and the city?', 'Sarah Jessica Parker', 'Renée Zellweger', 'Natalie Portman', 'Angelina Jolie'),
('hard', '¿A qué temperatura se hace sólido el aceite de oliva?', '0 grados', '2 grados', '3 grados bajo cero', '10 grados bajo cero'),
('hard', '¿Qué personaje de una tragedia de Shakespeare ofreció su reino por un caballo?', 'Ricardo III', 'Falstaff', 'El rey Lear', 'Romeo'),
('hard', '¿Quién escribió Cuentos de amor, de locura y de muerte?', 'Quiroga', 'García Lorca', 'García Márquez', 'Cortázar'),
('hard', '¿Cuántos viajes a China hizo Marco Polo?', '1', '10', '5', '3'),
('hard', '¿Qué provincia tiene en su escudo 7 banderas argentinas?', 'Córdoba', 'La Pampa', 'Río Negro', 'La Rioja'),
('hard', '¿Cuántos poemas de amor son los de Neruda?', '20', '100', '30', '10'),
('hard', '¿Cuál fue el primer país en aprobar el sufragio femenino?', 'Uruguay', 'Argentina', 'Colombia', 'Chile'),
('hard', '¿Qué droga cocinan los protagonistas de Breaking Bad?', 'Metanfetamina', 'Efedrina', 'Cocaína', 'Marihuana'),
('easy', '¿Qué fútbolista tiene como apodo "La Pulga"?', 'Messi', 'Agüero', ' Higuaín', 'Mascherano'),
('easy', '¿Cuántas estrellas hay en el escudo del Capitán América?', '1', '2', '0', '50'),
('easy', '¿Cuántas alas tiene una mosca?', '2', '4', '6', '8'),
('easy', '¿En qué país se jugará la copa del mundo de futbol 2022?', 'Catae', 'Brasil', 'Reino Unido', 'Alemania'),
('hard', '¿Cuántos ojos tiene una iguana?', '3', '2', '1', '4'),
('easy', 'Marlin ¿Qué es de nemo?', 'Padre', 'Hermano', 'Hijo', 'Amigo'),
('easy', '¿Cuántos hijos tiene Ned Flanders en "Los Simpson?', '2', '1', '3', '0'),
('medium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('medium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('medium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('medium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('medium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('medium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),