/* PREGUNTAS  TODO:pregunta unique*/
INSERT INTO preguntas (difficulty, question, correct_answer, incorrect_answer1, incorrect_answer2, incorrect_answer3) VALUES
('easy', '¿En qué ciudad de la distopía del futuro alternativo de Half-Life 2 empiezas por primera vez?', 'Ciudad 17', 'Ciudad 18', 'Ciudad 6', 'Ciudad 45'),
('easy', '¿Cuál de los siguientes personajes NO es una candidata a matrimonio en el juego Stardew Valley?', 'Caroline', 'Haley', 'Leah', 'Abigail'),
('easy', 'La "invasión británica" fue un fenómeno cultural en la música donde las bandas de chicos británicos se hicieron populares en los EE. UU. ¿En qué década?', 'Años 50', 'Años 30', 'Años 40', 'Años 60'),
('easy', '¿ Cuál de las siguientes fuentes del derecho es la principal?', 'Constitución Nacional', 'leyes', 'Decretos', 'Tratados internacionales'),
('medium', '¿Cuántos balones de oro gano Lionel Andrés Messi?', '7', '5', '6', '8'),
('hard', '¿Cuál es la característica de un nudo gordiano?', 'Difícil de desatar', 'Fácil de desatar', 'Muscular', 'Psicológico / emocional'),
('easy', '¿Cuál de los siguientes no es el nombre de los hijos de Leo Messi y Antonela Roccuzzo?', 'Marcos', 'Mateo', 'Ciro', 'Thiago'),
('easy', '¿Qué hay en el centro de nuestra galaxia?', 'Un agujero negro', 'Una supernova', 'Un Cuasar', 'Un agujero de gusano'),
('easy', '¿Cuántos álbumes de estudio ha lanzado el dúo Daft Punk?', '4', '1', '2', '5'),
('easy', 'En "Mario & Sonic en los Juegos Olímpicos", ¿los personajes se dividen en cuántos tipos?', '4', '3', '5', '6'),
('easy', '¿Cuándo se estrenó la película "Con Air: Riesgo en el Aire"?', '1997', '1990', '1985', '1999'),
('easy', '¿Cómo se llama la isla en la que está construido "Jurassic Park"?', 'Isla Nublar', 'Isla Pena', 'Isla Sorna', 'Isla Muerta'),
('easy', '¿Cuál es la raíz cuadrada de 49?', '7', '9', '12', '4'),
('medium', '¿En qué motor de videojuegos se ejecuta el videojuego Quake 2?', 'iD Tech 2', 'iD Tech 3', 'iD Tech 1', 'Unreal engine'),
('easy', '¿Cuántos kilobytes hay en un gigabyte (en decimal)?', '1000000', '1048576', '1024', '1000'),
('easy', '¿Cómo se llamaba el submarino del capitán Nemo en "20.000 leguas de viaje submarino"?', 'El Nautilus', 'El Neptuno', 'El poseidon', 'La Atlántida'),
('easy', '¿Qué pintura no fue hecha por Vincent Van Gogh?', 'La novena ola', 'Dormitorio En Arles', 'Noche estrellada', 'Terraza del Café por la Noche'),
('hard', '¿Terry Gilliam fue un animador que trabajó con qué grupo de comedia británico?', 'Monty Python', 'Las golosinas', 'La Liga de los Caballeros', 'Los Penny Dreadfuls'),
('easy', '¿Cuál de los siguientes países no fue una potencia de eje durante la Segunda Guerra Mundial?', 'Unión Soviética', 'Japón', 'Alemania', 'Italia'),
('hard', '"Doctor Jones", "Turn Back Time" y "Barbie Girl" fueron los números uno del Reino Unido para qué grupo de Eurodance?', 'Agua', 'Vengaboys', 'Eiffel 65', 'Sash!'),
('easy', '¿Quién ganó el Campeonato Mundial de Pilotos de Fórmula 1 de 2016?', 'Nico Rosberg', 'Lewis Hamilton', 'Max Verstappen', 'Kimi Raikkonen'),
('hard', 'En el programa de televisión "Cheers", ¿Sam Malone fue un ex lanzador de relevo para qué equipo de béisbol?', 'Medias Rojas de Boston', 'Mets de Nueva York', 'Cerveceros de Milwaukee', 'Orioles de Baltimore'),
('easy', '¿Qué empresa desarrolla la serie de juegos de ritmo Rock Band?', 'Harmonix', 'Konami', 'Activision', 'Electronics Arts'),
('easy', '¿Qué álbum colaborativo fue lanzado por Kanye West y Jay-Z en 2011?', 'Mira el trono', 'Relativas distancias', 'Negocios inconclusos', 'Qué momento para estar vivo'),
('easy', '¿Quién en la mitología griega, quién llevó a los argonautas en busca del Vellocino de oro?', 'Jason', 'Castor', 'Dédalo', 'Odiseo'),
('easy', '¿Quién resulta ser el verdadero vencedor en la Batalla de Armageddon en Mortal Kombat?', 'Shao Kahn', 'Liu Kang', 'Shang Tsung', 'Raiden'),
('easy', '¿En qué país se fabricó el Trabant 601?', 'Alemania del Este', 'Unión Soviética', 'Hungría', 'Francia'),
('easy', '¿Cuál de estos NO es el nombre de un álbum lanzado por la cantautora inglesa Adele?', '12', '21', '19', '25'),
('easy', 'En el videojuego "Postal 2", ¿cómo se llama el perro de Postal Dude?', 'Champ', 'Krotchy', 'Snoopy', 'Duke'),
('easy', 'Cuando alguien no tiene experiencia, se dice que es de qué color.', 'Verde', 'Azul', 'Rojo', 'Amarillo'),
('easy', '¿La rinoplastia es un procedimiento quirúrgico en qué parte del cuerpo humano?', 'Nariz', 'Orejas', 'Barbilla', 'Cuello'),
('easy', '¿En qué país se encuentra Cory in the House?', 'Estados Unidos', 'Venezuela', 'Inglaterra', 'Canadá'),
('easy', '¿Qué actriz se casó con Michael Douglas en 2000?', 'Catherine Zeta Jones', 'Ruth Jones', 'Pam Ferris', 'Sara Sugarman'),
('easy', '¿De dónde es originario el origami?', 'China', 'Japón', 'Corea del Norte', 'Corea del Sur'),
('easy', '¿Quién es el cantante principal de Green Day?', 'Billie Joe Armstrong', 'Mike Dirnt', 'Sean Hughes', 'Tré Cool'),
('easy', '¿Cuáles de estos países permanecieron neutrales durante la Segunda Guerra Mundial?', 'Suiza', 'Reino Unido', 'Italia', 'Francia'),
('easy', '¿Que informático estadounidense creo el lenguaje de programación C', 'Dennis Ritchie', 'al-Khwārizmī', 'Tim Berners Lee', 'Willis bienes'),
('easy', '¿En qué año llegó Colón a América?', '1492', '1429', '1592', '1542'),
('medium', '¿En qué año se hundió el Titanic?', '1912', '1913', '1911', '1914'),
('hard', 'En 2013, ¿la estrella del pop virtual Hatsune Miku tenía un patrocinio con qué cadena de pizzas?', 'Dominos', 'Sabarros', 'Pizza Hut', 'Papa Johns'),
('easy', '¿Qué cervecería de propiedad estadounidense lideró el país en ventas por volumen en 2015?', 'DG Yuengling and Son, Inc', 'Boston Beer Company', 'Miller Coors', 'Anheuser Busch'),
('easy', '¿Cuál es el formato de imagen preferido para los logotipos en la base de datos de Wikimedia?', '.svg', '.jpeg', '.gif', '.jpeg'),
('easy', '¿Cuántos colores hay en un arcoíris?', '7', '8', '9', '9'),
('easy', '¿Cuántos cromosomas hay en las células del cuerpo humano?', '23', '22', '21', '24'),
('easy', '¿Cuál de estos NO es un personaje jugable en el videojuego Overwatch de 2016?', 'Invoker', 'Winston', 'Mercy', 'Zenyatta'),
('easy', '¿Qué obra de Shakespeare inspiró el musical "West Side Story"?', 'Romeo y Julieta', 'Macbeth', 'Othello', 'Hamlet'),
('easy', '¿Cual es la capital de Indonesia?', 'Jacarta', 'Medan', 'Palembang', 'Bandung'),
('easy', '¿Cuál es la capital de España?', 'Madrid', 'Toledo', 'Barcelona', 'Sevilla'),
('easy', '¿Cuál es el nombre en clave del sistema operativo móvil Android 7.0?', 'Nougat', 'Marshmallow', 'Ice Cream Sandwich', 'Jelly Bean'),
('easy', '¿La imagen de qué presidente aparece en el raro billete de 2 dólares estadounidense?', 'Thomas Jefferson', 'Martin Van Buren', 'John Quincy Adams', 'Ulysses Grant'),
('easy', '¿El hielo seco es la forma sólida de qué sustancia?', 'Dióxido de carbono', 'Amoníaco', 'Nitrógeno', 'Oxígeno'),
('hard', '¿Cuál es el apellido de la protagonista femenina principal de Final Fantasy VIII?', 'Heartilly', 'Almasy', 'Trepe', 'Loire'),
('easy', '¿Quién escribió "Harry Potter"?', 'J.K. Rowling', 'J.R.R. Tolkien', 'Terry Pratchett', 'Daniel Radcliffe'),
('easy', '¿Qué edad tenía Adolf Hitler cuando murió?', '56', '65', '45', '43'),
('hard', '¿En qué año se lanzó el primer juego de "Mass Effect"?', '2007', '2010', '2008', '2008'),
('easy', '¿Quién es el protagonista principal de Dead Space?', 'Isaac Clarke', 'Jefe principal', 'Comandante Shepard', 'Gordon Freeman'),
('easy', '¿En que año se lanzó Left 4 Dead 2?', '2009', '2010', '2008', '2007'),
('easy', '¿Con cuántos países comparte frontera terrestre Estados Unidos?', '2', '3', '1', '4'),
('easy', 'En un tablero de dardos, ¿qué número está directamente enfrente del número 1?', '19', '20', '12', '15'),
('hard', '"Minecraft" salió de la versión beta en 2011 durante una convención celebrada ¿en qué ciudad?', 'Las Vegas', 'Paris', 'Bellevue', 'London'),
('easy', '¿La serie de HBO "Game of Thrones" se basa en qué serie de libros?', 'Canción de hielo y fuego', 'Harry Potter', 'La rueda del tiempo', 'Nacidos de la bruma'),
('easy', '¿Cómo se llamaba el primer satélite terrestre artificial, lanzado por la Unión Soviética en 1957?', 'Sputnik 1', 'Voskhod 3KV', 'Zenit-2', 'Soyuz 7K-OK'),
('easy', '¿De qué color es el círculo de la bandera japonesa?', 'Rojo', 'Amarillo', 'Blanco', 'Negro'),
('medium', 'En la serie de videojuegos "Worms", ¿cuál de estas armas se ve afectada por el viento?', 'Bazuca', 'Ataque aéreo', 'Mortero', 'Granada'),
('easy', '¿Quién descubrió la penicilina?', 'Alexander Flemming', 'Marie Curie', 'Louis Pasteur', 'Alfred Nobel'),
('easy', 'En la mayoría de los videojuegos de FPS como Counter-Strike, ¿disparar a qué parte del cuerpo causa el mayor daño?', 'Cabeza', 'Brazo', 'Pecho', 'Pierna'),
('easy', '¿En qué año se lanzó League of Legends?', '2009', '2003', '2010', '2001'),
('easy', 'Which popular First Person Shooter (FPS) franchise, got a Real Time Strategy (RTS) game developed based on its universe?', 'Halo', 'Call of Duty', 'Battlefield', 'Borderlands'),
('medium', '¿En qué medio se creó "Clannad" por primera vez?', 'Novela visual', 'Anime', 'Novela ligera', 'Manga'),
('easy', '¿Cuántos planetas componen nuestro Sistema Solar?', '8', '9', '7', '6'),
('easy', 'Según Sherlock Holmes, "si eliminas lo imposible, lo que quede, por improbable que sea, debe ser el ....', 'Verdad', 'Respuesta', 'Causa', 'Fuente'),
('easy', '¿Cuál es el alter-ego del personaje de los cómics de DC "Superman"?', 'Clark Kent', 'Bruce Wayne', 'John Jones', 'Arthur Curry'),
('easy', '¿Qué animal participa en el experimento mental más famoso de Schrödinger?', 'Gato', 'Perro', 'Raton', 'Mariposa'),
('easy', '¿Cuál de estas criaturas mitológicas es mitad hombre y mitad caballo?', 'Centauro', 'Gorgona', 'Minotauro', 'Pegaso'),
('medium', '¿Quién es el protagonista del juego "The Walking Dead: Season One"?', 'Lee Everett', 'Clementina', 'Kenny', 'Rick Grimes'),
('hard', '¿Quién es el creador de la serie Super Smash Bros?', 'Masahiro Sakurai', 'Reggie Fils-Aime', 'Hideo Kojima', 'Bill Trinen'),
('hard', '¿En qué año se lanzó el juego "Fallout"?', '1997', '1998', '1999', '2000'),
('medium', '¿Cuál de los siguientes no es un personaje de la serie Street Fighter?', 'Mai Shiranui', 'Laura Matsuda', 'Sakura Kasugano', 'Ibuki'),
('easy', '¿Qué actor interpreta a "Walter White" en la serie "Breaking Bad"?', 'Bryan Cranston', 'Andrew Lincoln', 'Aaron Paul', 'RJ Mitte'),
('medium', '¿Cómo se llama el corgi del anime Cowboy Bebop?', 'Einstein', 'Joel', 'Rocket', 'Edward'),
('medium', '¿Cuándo se fundó Marvel Comics?', '1939', '1932', '1936', '1951'),
('easy', '¿Cuántas patas tienen las mariposas?', '6', '4', '8', '0'),
('easy', '¿Qué cantidad de bits equivale comúnmente a un byte?', '8', '64', '1', '1024'),
('easy', '"La primera regla es: no hablas de eso" ¿es una referencia a qué película?', 'Club de la lucha', 'American Pie', 'La isla', 'Lo Inimaginable'),
('easy', '¿Cuál de estos personajes es la mascota de la empresa de videojuegos SEGA?', 'Sonic', 'Alex Jidd', 'Opa-Opa', 'Mario Bros'),
('medium', '¿Cuál es el título de la canción en el menú principal de Halo?', 'Halo', 'Shadows', 'Suite Autumn', 'Opening Suite'),
('easy', '¿Cuál fue el segundo Pokémon de Ash Ketchum?', 'Caterpie', 'Pikachu', 'Pidgey', 'Charmander'),
('easy', '¿En qué empresa trabajaba Gabe Newell antes de fundar Valve Corporation?', 'Microsoft', 'Yahoo', 'Google', 'Apple'),
('medium', '¿Cuál es la profesión de la madre de Elon Musk, Maye Musk?', 'Modelo', 'Profesora', 'Programadora', 'Abogada'),
('easy', '¿Cuántos juegos de la serie Crash Bandicoot se lanzaron en la Playstation original?', '5', '6', '3', '4'),
('easy', '¿Cual es la capital de Jamaica?', 'Kingston', 'San Juan', 'Bridgetown', 'Nueva Delhi'),
('easy', '¿Cuántas estrellas tiene la bandera de Nueva Zelanda?', '4', '5', '2', '0'),
('easy', 'En South Park, ¿cuál es el apellido de Stan?', 'Marsh', 'Stotch', 'Broflovski', 'Tweak'),
('easy', 'Cuando alguien es cobarde, ¿de qué color se dice que tiene el vientre', 'Amarillo', 'Verde', 'Azul', 'Rojo'),
('medium', '¿Cuál de los siguientes NO es uno de los personajes principales del modo historia de Grand Theft Auto V?', 'Tommy Vercetti', 'Trevor Phillips', 'Michael de Santa', 'Franklin Clinton'),
('medium', 'En el anime "My Hero Academia", ¿qué personaje se muestra con la capacidad de manipular la gravedad?', 'Uraraka', 'Bakugo', 'Deku', 'Asui'),
('easy', 'El 71% de la superficie terrestre está formada por', 'Agua', 'Tierra', 'Desiertos', 'Bosques'),
('easy', '¿Cuántos lados tiene un heptágono?', '7', '8', '6', '5'),
('hard', '¿Cuántas obras de teatro se considera en general que Shakespeare ha escrito?', '37', '54', '43', '36'),
('easy', '¿Cómo se llama el papá de Harry Potter?', 'James Potter', 'Hairy Potter Sr.', 'Frank Potter', 'Joey Potter'),
('easy', '¿Qué elemento tiene el símbolo químico "Fe"?', 'Hierro', 'Plata', 'oro', 'Aluminio'),
('easy', '¿En qué año se produjo el desplome de Wall Street?', '1929', '1930', '1932', '1925'),
('easy', '¿Quién creó la serie "Metal Gear"?', 'Hideo Kojima', 'Gunpei Yokoi', 'Hiroshi Yamauchi', 'Shigeru Miyamoto'),
('easy', '¿Qué nombre se le da al personaje principal Chihiro en la película de 2001 "El viaje de Chihiro"?', 'Sen (mil)', 'Ichiman (diez mil)', 'Hyaku (cien)', 'Juu (diez)'),
('easy', '¿Qué número primo sigue después del 19?', '23', '27', '25', '21'),
('easy', '¿Cuál era el apellido de Dorothy en "El mago de Oz"?', 'Gale', 'Perkins', 'Parker', 'Day'),
('easy', '¿Qué país del Reino Unido tiene un dragón en su bandera?', 'Gales', 'Escocia', 'Inglaterra', 'Irlanda del Norte'),
('easy', '¿Qué equipo ganó la Copa Mundial de la FIFA 2014 en Brasil?', 'Alemania', 'Brasil', 'España', 'Argentina'),
('easy', '¿Cuántas estrellas tiene la bandera de la Unión Europea?', '12', '14', '10', '16'),
('hard', '¿Cómo se llama el león de peluche del anime Bleach?', 'Kon', 'Chad', 'Jo', 'Urdio'),
('easy', '¿Qué ciudad es la capital de los Estados Unidos de América?', 'Washington DC', 'Seattle', 'Los Angeles', 'Albany'),
('easy', '¿Qué estado de EE. UU. Tiene la mayor población?', 'California', 'Nueva York', 'Florida', 'Texas'),
('medium','¿Quién es el personaje principal de "La parábola de Stanley"?', 'Stanley', 'El jefe', 'El narrador', 'Nick'),
('easy', '¿Cuántos puntos hay en un solo dado?', '21', '24', '18', '23'),
('easy', '¿En qué año comenzó la Primera Guerra Mundial?', '1914', '1919', '1925', '1905'),
('easy', '¿Cuántas cuerdas tiene un violonchelo?', '4', '5', '8', '6'),
('easy', '¿Cuál es el nombre del robot naranja y blanco en "Star Wars: El despertar de la fuerza"?', 'BB-8', 'R2-D2', 'BB-3', 'C3PO'),
('easy', '¿Qué signo del zodíaco está representado por un par de escamas?', 'Libra', 'Sagitario', 'Aries', 'Capricornio'),
('medium', '¿Con qué empresa cooperó Valve en la creación de Vive?', 'HTC', 'Oculus', 'Razer', 'Google'),
('hard', '¿Cuál es el símbolo elemental del mercurio?', 'Hg', 'Me', 'Hy', 'Mc'),
('easy', '¿Cuándo se lanzó el iPhone?', '2007', '2006', '2005', '2004'),
('easy', '¿Quién es el principal antagonista de la franquicia Portal?', 'GLaDOS', 'Wheatley', 'Chell', 'Rick'),
('hard', 'En el juego Dark Souls, ¿cuál es el nombre de la región en la que te encuentras durante la mayor parte del juego?', 'Lordran', 'Drangleic', 'Oolacile', 'Catarina'),
('hard', 'En la película de animacion japonesa de 2012 "Niños lobo", ¿cómo se llaman los niños lobo?', 'Ame y Yuki', 'Ame y Hana', 'Chuck y Anna', 'Hana y Yuki'),
('medium', '¿Cuántos huesos hay en el cuerpo humano?', '206', '209', '200', '203'),
('easy', 'En la Copa Mundial de la FIFA 2014, ¿cuál fue el marcador final en el partido Brasil - Alemania?', '1-7', '2-6', '1-5', '1-6'),
('easy', '¿Cuál de los siguientes componentes sanguíneos forma un tapón en el lugar de las lesiones?', 'Plaquetas', 'globulos rojos', 'globulos blancos', 'Plasma'),
('easy', '¿Hipocampo es el nombre latino de qué criatura marina?', 'Caballo de mar', 'Delfín', 'Ballena', 'Pulpo'),
('hard', '¿Cuántos dientes tiene un conejo adulto?', '28', '24', '26', '30'),
('hard', '¿Cuántas zonas horarias tiene China?', '1', '2', '3', '4'),
('easy', 'En béisbol, ¿cuántas veces se debe lanzar la pelota fuera de la zona de strike antes de que se camine al bateador?', '4', '2', '3', '1'),
('easy', '¿Cuál es el apellido de Edward y Alphonse en el anime Fullmetal Alchemist?', 'Elric', 'Elwood', 'Ellis', 'Eliek'),
('medium', '¿Cuál de las siguientes es una clase del juego "Hearthstone"?', 'Sacerdote', 'Clérigo', 'Sabio', 'Monje'),
('easy', '¿La mascota de qué restaurante es un payaso?', 'Burger king', 'McDonalds', 'Whataburger', 'Sonic'),
('hard', '¿Qué estudio de animación animó el anime de 2016 "Mob Psycho 100"?', 'Bones', 'Shaft', 'A-1 Pictures', 'Madhouse'),
('easy', '¿Aproximadamente cuántos años tiene la Tierra?', '4.5 mil millones', '2.5 mil millones', '5,5 mil millones', '3,5 mil millones'),
('mediium', '¿Quién es el creador de la serie manga "One Piece"?', 'Eiichiro Oda', 'Hayao Miyazaki', 'Yoshihiro Togashi', 'Masashi Kishimoto'),
('mediium', 'En la serie de videojuegos Portal, ¿con qué nombre se fundó Aperture Science a principios de la década de 1940?', 'Aperture Fixtures', 'Aperture Lavatories', 'Wheatley Laboratories', 'Science Innovator'),
('mediium', '¿Cuál es el nombre de la primera película de "Star Wars" por orden de lanzamiento?', 'Una nueva esperanza', 'La amenaza fantasma', 'La venganza de los Sith', 'El despertar de la fuerza'),
('mediium', '¿Cuál es la fórmula química del amoniaco?', 'NH3', 'CH4', 'CO2', 'NO3'),
('medium', '¿En qué año surgió la banda de rock Queen?', '1970', '1973', '1968', '1975'),
('medium', '¿Quién es miembro de la banda británica Queen?', 'Todas son correctas', 'Freddie Mercury', 'Roger Taylor', 'John Deacon'),
('medium', '¿En qué año falleció Freddie Mercury?', '1991', '1981', '1993', '1987'),
('medium', '¿En qué año se estrenó la película Mujer Bonita?', '1990', '1999', '1992', '1994'),
('medium', '¿En qué año se estrenó la película Novia Fugitiva?', '1999', '1993', '1995', '1996'),
('medium', '¿En qué año se formó la banda argentina de rock Soda Stereo?', '1982', '1988', '1980', '1983'),
('medium', '¿En qué año se separó Soda Stereo?', '1997', '1994', '1995', '1992'),
('medium', '¿Cómo se llama el primer álbum de estudio de Soda Stereo?', 'Soda Stereo', 'Doble vida', 'Nada personal', 'Signos'),
('medium', '¿En qué año ocurrió el robo del siglo que dio origen a la película?', '2006', '2000', '2002', '2003'),
('medium', '¿Cuántos músculos tiene el ser humano?', 'Más de 600', '400 a 500', '300 a 400', '500 a 600')
('hart', '¿Cuántos tipos de tejido muscular existen?', '3', '2', '4', '1'),
('hart', '¿En qué año termino la segunda guerra mundial?', '1945', '1943', '1940', '1939'),
('medium', '¿Cuál es el país más grande del mundo?', 'Rusia', 'China', 'India', 'Estados Unidos'),
('hart', '¿En qué año empezó la segunda guerra mundial?', '1939', '1943', '1940', '1945'),
('medium', '¿Dónde hubo fuego…?', 'Cenizas quedan', 'Cenizas fueron', 'Cenizas hay', 'Ninguna es correcta'),
('medium', '¿En casa de herrero?', 'Cuchillo de palo', 'Cuchillo de madera', 'Ninguna es correcta', 'Cuchillo desafilado'),
('medium', '¿Cuál es un número primo?', '19', '47', '71', 'Todas son correctas'),
('hart', '¿Cuál es un numero compuesto?', '99', '11', '59', '23'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),
('mediium', '¿pregunta?', 'RespuestaCorrecta', 'RespuestaIncorrecta1', 'RespuestaIncorrecta2', 'RespuestaIncorrecta3'),